version: '3'
services:
  # docker-compose -f docker-compose.yml up --detach --build  ## for recreating th
  api:
    # image: zelejs/app-openjre11:latest
    image: registry.docker.internal:5000/gmic:api
    container_name: gmic-api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./attachments:/attachments
      # - ./api:/webapps
    environment:
      DL_ROLLBACK: 'gmic-cad-artifact-1.0.0-standalone.jar'
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    depends_on: 
      - mysqlserver

  web:
    # image: daocloud.io/library/nginx:latest
    image: registry.docker.internal:5000/gmic:web
    container_name: web
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./web/dist/admin:/usr/share/nginx/html
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  mysqlserver:
    container_name: mysqlserver
    image: 'daocloud.io/library/mysql:5.7'
    privileged: true
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: 'cinema'
      MYSQL_ROOT_PASSWORD: 'rootAZaz@123'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d/sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    container_name: nginx
    image: 'daocloud.io/library/nginx:latest'
    privileged: true
    restart: always
    ports:
      - 80:80
      # - 443:443
      # - 23306:23306
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cert:/cert
      - ./images:/images
      - ./attachments:/usr/share/nginx/html/attachments
      - ./public:/usr/share/nginx/html/public
    environment:
      TZ: "Asia/Shanghai"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        
  mysqlbackup:
    image: zelejs/mysqlbackup 
    container_name: mysqlbackup
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysqlbackup/data:/var/mysqlbackup/data
      - ./mysqlbackup/log:/var/mysqlbackup/log
    environment:
      MYSQL_DB: cinema
      TZ: Asia/Shanghai
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root 
      MYSQL_USER_PASSWORD: rootAZaz@123
      CRONTAB_DAILY_HOUR: 3
      CRONTAB_DAILY_MIN: 25
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  # redis:
  #   container_name: redis
  #   image: 'daocloud.io/library/redis:3.2.9'
  #   environment:
  #     TZ: "Asia/Shanghai"
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/conf:/usr/local/etc/redis
  #   command:
  #     redis-server /usr/local/etc/redis/redis.conf
  #datagear:
  #  image: 'zelejs/datagear'
  #  container_name: datagear
  #  volumes:
  #    - ./datagear/logs:/usr/local/tomcat/logs

networks: 
  default:
    gmic_cad_network:
